config/routes.rb
Rails.application.routes.draw do
devise_for :restaurants
# , controllers: {
#   sessions:      'restaurants/sessions',
#   passwords:     'restaurants/passwords',
#   registrations: 'restaurants/registrations'
# }
devise_for :customers
# , controllers: {
#   sessions:      'customers/sessions',
#   passwords:     'customers/passwords',
#   registrations: 'customers/registrations'
# }

  authenticated :customer do
    root 'customers/restaurants#index', as: :customer_authenticated_root
  end

  authenticated :restaurant do
    root 'restaurants/reservations#index', as: :restaurant_authenticated_root
  end
  root to: 'pages#home'
  # resources :restaurants, only: [:index, :show] do
  #   resources :reservations, only: [:create]
  # end
  namespace :restaurants do
    resources :reservations, only: [:index, :show] do
      member do
        put "confirm"
        put "decline"
      end
    end
    resources :profiles, only: [:edit, :update]
    resources :chefs, only: [:index, :edit, :update, :destroy]
    resources :menus, only: [:index, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show]
    resources :images, only: [:index, :update, :destroy]
    # get "reservations/:id/confirm", to: "reservations#confirm"
  end

  namespace :customers do
    resources :restaurants, only: [:index, :show] do
      resources :reservations, only: [:create] do
        resources :payments, only: [:new, :create]
      end
    end
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :reservations, only: [:index] do
      member do
        put "cancel"
      end
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  belongs_to :customer
  monetize :amount_cents
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :picture, PictureUploader

  has_many :reviews
  has_many :menus
  has_many :chefs
  has_many :images
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # monetize :price_cents

  # skip_callback :commit, :after, :remove_previously_stored_avatar
end

app/controllers/customers/reservations_controller.rb
class Customers::ReservationsController < ApplicationController
  before_action :set_restaurant, only: [:show, :create]
  before_action :set_reservation, only: [:show, :cancel]

  def index
    @reservations = policy_scope [:customer, Reservation]
  end

  def show
    @reservation = current_customer.reservations.where(status: 'paid').find(params[:id])
  end

  def cancel
    authorize [:customer, @reservation]
    @reservation.status = "canceled"
    @reservation.save
    redirect_to customers_reservations_path
  end

  def create
    @reservation = Reservation.new
    @reservation.status = "pending"
    @reservation.customer = current_customer
    @reservation.restaurant = @restaurant
    # @reservation.restaurant.price = restaurant.price,
    authorize [:customer, @reservation]
    if @reservation.save
      redirect_to new_customers_restaurant_reservation_payment_path(@reservation.restaurant.id, @reservation.id)
    else
      @markers = [{
        lat: @restaurant.latitude,
        lng: @restaurant.longitude
      }]

      render "customers/restaurants/show"
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:status)
  end
end




#   def index
#   end

#   def show
#     authorize @reservation
#     @customer = Customer.find(@reservation.customer_id)
#   end

#   def confirm
#     @reservation.status = "confirmed"
#     @reservation.save
#     redirect_to restaurants_reservations_path
#   end

#   def decline
#     skip_policy_scope
#     @reservation.status = "declined"
#     @reservation.save
#     redirect_to restaurants_reservations_path
#   end

app/controllers/customers/restaurants_controller.rb
class Customers::RestaurantsController < ApplicationController
  skip_before_action :should_authenticate_customer!, only: [:index, :show]

  def index
    skip_policy_scope
    @restaurants = Restaurant.all

    if params[:query].present?
      @restaurants = Restaurant.where.not(latitude: nil, longitude: nil).search_by_name(params[:query])
    else
      @restaurants = Restaurant.where.not(latitude: nil, longitude: nil)
    end
    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
      }
    end

  end

  def show
    skip_policy_scope
    @restaurant = Restaurant.find(params[:id])

    @markers = [{
      lat: @restaurant.latitude,
      lng: @restaurant.longitude
    }]

    @reservation = Reservation.new
    @customer = current_customer
    @reservation.restaurant = @restaurant
    @reservation.customer = @customer

  end

   private

  def equipment_params
    params.require(:restaurant).permit(:category, :name, :cuisine, :city, :category)
  end
end

app/controllers/restaurants/chefs_controller.rb
class Restaurants::ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :update, :destroy]

  def index
    @chefs = policy_scope Chef
  end

  def edit
    authorize @chef
  end

  def update
    skip_policy_scope
    @chef.update(chef_params)
    redirect_to restaurants_chefs_path
  end

  def destroy
    skip_policy_scope
    @chef.destroy
    redirect_to restaurants_chefs_path
  end

  private

  def chef_params
    params.require(:chef).permit(:name, :avatar, :profile)
  end


  def set_chef
    @chef = Chef.find(params[:id])
  end

end

app/controllers/restaurants/confirmations_controller.rb
# frozen_string_literal: true

class Restaurants::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end

end

app/controllers/restaurants/images_controller.rb
class Restaurants::ImagesController < ApplicationController
  def index
    skip_policy_scope
    @images = Image.all
  end

  def new
    @image = Image.build
  end

  private

  def image_params
  params.require(:image).permit({image_url: []})
  end
end

app/controllers/restaurants/menus_controller.rb
class Restaurants::MenusController < ApplicationController
  before_action :set_menu, only: [:edit, :update, :destroy]

  def index
    @menus = policy_scope Menu
  end

  def edit
    authorize @menu
  end

  def update
    skip_policy_scope
    @menu.update(menu_params)
    redirect_to restaurants_menus_path
  end

  def destroy
    skip_policy_scope
    @menu.destroy
    redirect_to restaurants_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :price, :image)
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end
end

app/controllers/restaurants/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Restaurants::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

end

app/controllers/restaurants/passwords_controller.rb
# frozen_string_literal: true

class Restaurants::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

end

app/controllers/restaurants/profiles_controller.rb
class Restaurants::ProfilesController < ApplicationController
  def edit
    skip_policy_scope
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    skip_policy_scope
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    authorize @restaurant
    redirect_to root_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:category, :dresscode, :opening_hours, :style, :cuisine, :tel, :city, :street, :zipcode, :picture)
  end
end

app/controllers/restaurants/registrations_controller.rb
# frozen_string_literal: true

class Restaurants::RegistrationsController < Devise::RegistrationsController
  include Accessible
  # skip_before_action :check_customer, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:category])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:category])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/restaurants/reservations_controller.rb
class Restaurants::ReservationsController < ApplicationController
  before_action :set_restaurant, only: [:show, :confirm]
  before_action :set_reservation, only: [:show, :confirm, :decline]

  def index
    @reservations = policy_scope Reservation
  end

  def show
    authorize @reservation
    @customer = Customer.find(@reservation.customer_id)
  end

  def confirm

    @reservation.status = "confirmed"
    authorize @reservation

    @reservation.save
    redirect_to restaurants_reservations_path
  end

  def decline
    # skip_policy_scope
    @reservation.status = "declined"
    authorize @reservation

    @reservation.save
    redirect_to restaurants_reservations_path
  end

  private

  def set_restaurant
    @restaurant = current_restaurant
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:status)
  end

end

app/controllers/restaurants/reviews_controller.rb
class Restaurants::ReviewsController < ApplicationController
  def index
    skip_policy_scope
    @reviews = policy_scope Review
    # @reviews = Review.all
  end
end

app/controllers/restaurants/sessions_controller.rb
# frozen_string_literal: true

class Restaurants::SessionsController < Devise::SessionsController
  include Accessible
  # skip_before_action :check_customer, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/restaurants/unlocks_controller.rb
# frozen_string_literal: true

class Restaurants::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end

end

app/views/restaurants/reservations/confirm.html.erb
<div class="container">
  <h2>RESTAURANTS::RESERVATION#EDIT</h2>
  <p>Find me in app/views/restaurants/reservations/show.html.erb</p>
  <hr>
  <p> <%= current_restaurant.email %></p>
  <p> Reservation ID: <%= @reservation.id %></p>

  <%# simple_form_for(@reservation, url: restaurants_reservation_path(@reservation), method: :put) do |f| %>
      <%# f.input :status%>
      <%# f.submit "Save", class: "btn btn-primary" %>
      <%# end %>
  <%= link_to "Confirm", confirm_restaurants_reservation_path(@reservation), class: "btn btn-primary", method: :put %>
</div>

app/views/restaurants/reservations/index.html.erb
<div class="container">
  <div class="wrapper-white">
    <h1>Restaurant Admin Page</h1>

    <%= link_to "Change Password", edit_restaurant_registration_path, class: "btn btn-primary" %>
    <%= link_to "Edit Profile", edit_restaurants_profile_path(current_restaurant), class: "btn btn-warning" %>
    <%= link_to "Chefs", restaurants_chefs_path, class: "btn btn-info" %>
    <%= link_to "Menus", restaurants_menus_path, class: "btn btn-success" %>
    <%= link_to "Review", restaurants_reviews_path, class: "btn btn-primary" %>
    <%= link_to "Image", restaurants_images_path, class: "btn btn-danger" %>

    <hr>

    <div class="row">
        <div class="card-reservation">
          <h3>Pending</h3>
          <% @reservations.each do |reservation| %>
            <% if reservation.status == "pending" %>
              <p> <%= reservation.time %>
                  time: <%= reservation.time %>
                  seats: <%= reservation.seats %>
                  name: <%= reservation.customer.name %>
                  request: (<%= reservation.request %>) </p>
              <p> <%= link_to "Reservation Detail", restaurants_reservation_path(reservation) %> </p>
            <% end %>
          <% end %>
        </div>

        <hr>

        <div class="card-reservation">
          <h3>Confirmed</h3>
          <% @reservations.each do |reservation| %>
            <% if reservation.status == "confirmed" %>
              <p> time: <%= reservation.time %> </p>
              <p> <%= link_to reservation, restaurants_reservation_path(reservation) %> </p>
            <% end %>
          <% end %>
        </div>

        <hr>

        <div class="card-reservation">
          <h3>Declined</h3>
          <% @reservations.each do |reservation| %>
            <% if reservation.status == "declined" %>
              <%= reservation.time %>
              <p> <%= link_to reservation, restaurants_reservation_path(reservation) %>
            <% end %> </p>
          <% end %>
        </div>
    </div>

    <br>
  </div>
  <br> <br>
</div>

app/views/restaurants/reservations/show.html.erb
<div class="container">
  <div class="wrapper-white">
    <h2>RESTAURANTS::RESERVATION#SHOW</h2>

    <%= @reservation %>
    <hr>
    <div class="">
      <p> Customer Name: <%= @customer.name %> </p>
      <p> Customer ID: <%= @reservation.customer_id %> </p>
      <p> Restaurant ID: <%= @reservation.restaurant_id %> </p>
      <p> Time: <%= @reservation.time %> </p>
      <p> Status: <%= @reservation.status %> </p>
      <p> Seats: <%= @reservation.seats %> </p>
      <p> Request: <%= @reservation.request %> </p>
      <% if @reservation.status =="pending" %>
        <%= link_to "Confirm", confirm_restaurants_reservation_path(@reservation), class: "btn btn-primary", method: :put %>
        <%= link_to "Decline", decline_restaurants_reservation_path(@reservation), class: "btn btn-success", method: :put %>
      <% end %>
      <hr>
    </div>
    <br>
    <%= link_to "Back", root_path, class: "btn btn-orange" %>
  </div>
  <br> <br>
</div>