config/routes.rb
Rails.application.routes.draw do
devise_for :restaurants
# , controllers: {
#   sessions:      'restaurants/sessions',
#   passwords:     'restaurants/passwords',
#   registrations: 'restaurants/registrations'
# }
devise_for :customers
# , controllers: {
#   sessions:      'customers/sessions',
#   passwords:     'customers/passwords',
#   registrations: 'customers/registrations'
# }

  authenticated :customer do
    root 'customers/restaurants#index', as: :customer_authenticated_root
  end

  authenticated :restaurant do
    root 'restaurants/reservations#index', as: :restaurant_authenticated_root
  end
  root to: 'pages#home'
  # resources :restaurants, only: [:index, :show] do
  #   resources :reservations, only: [:create]
  # end
  namespace :restaurants do
    resources :reservations, only: [:index, :show] do
      member do
        put "confirm"
        put "decline"
      end
    end
    resources :profiles, only: [:edit, :update]
    resources :chefs, only: [:index, :edit, :update, :destroy]
    resources :menus, only: [:index, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show]
    resources :images, only: [:index, :update, :destroy]
    # get "reservations/:id/confirm", to: "reservations#confirm"
  end

  namespace :customers do
    resources :restaurants, only: [:index, :show] do
      resources :reservations, only: [:create] do
        resources :payments, only: [:new, :create]
      end
    end
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :reservations, only: [:index] do
      member do
        put "cancel"
      end
    end
  end
end

app/views/shared/_card.html.erb
<div class="white-wrapper">
  <div class="container">
    <div class="row">
      <% @restaurants.each do |restaurant| %>
       <div class="col-xs-6">
        <% if restaurant.picture.blank? %>
          <div class="card-restaurant" style="background-color: black">
        <% else %>
          <div class="card-restaurant" style="background-image: url(<%= image_path restaurant.picture_url %>), linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
        <% end %>
          <div class="card-category"><%= restaurant.category %></div>
          <div class="card-name"><h2><%= restaurant.name %></h2></div>
          <div class="card-address">
            <i class="fas fa-map-marker-alt"></i>
            <p><%= restaurant.address %>, <%= restaurant.city %></p>
          </div class="btn-treehouse">
          <%= link_to "Details", customers_restaurant_path(restaurant), class: 'btn-treehouse card-link' %>
        </div>
        <br>
     </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-links">
    <a href="https://www.instagram.com/explore/tags/sports/?hl=en"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/sport/events/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/hashtag/sports?lang=en"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/authwall?trk=ripf&trkInfo=AQHQGYc3WWsr3gAAAWVDZHoYP626GLfJthc52gvlYAoZqTb7bdf0NRSuL55xgxDsxuXM107c7cEaJQ1lvnNCbT1HuRF78vsdM6mfvtQoKpLUc1lLsPwjMqyhxMMi5mKPalQdbxU=&originalReferer=https://www.google.com.ua/&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fjobs%2Fsports-jobs"><i class="fab fa-linkedin"></i></a>
  </div>

    <p class="footer-details"> Made with Le Wagon</p>

</div>

app/views/shared/_map.html.erb
<div class="map">
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
></div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if customer_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Restaurants", customers_restaurants_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Reservation", customers_reservations_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/random", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_customer_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% elsif restaurant_signed_in? %>

      <%= link_to "Admin Page", root_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/jenok", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_customer_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>


    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login as customer"), new_customer_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login as restaurant"), new_restaurant_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>